# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 10:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('bid', models.FloatField(blank=True, null=True, verbose_name='Bid')),
                ('bid_type', models.CharField(blank=True, choices=[('cpc', 'cpc'), ('cpm', 'cpm'), ('cpa', 'cpa'), ('cpv', 'cpv'), ('cpi', 'cpi')], max_length=255, null=True, verbose_name='Тип ставки')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('slug', models.CharField(max_length=255, verbose_name='URL')),
                ('bid_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('cpc', 'cpc'), ('cpm', 'cpm'), ('cpa', 'cpa'), ('cpv', 'cpv'), ('cpi', 'cpi')], max_length=255, null=True), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Channel', verbose_name='Канал'),
        ),
    ]
